insert into employees (name, employee_type_id, joining_date, team_id, status) values
('Aarav Sharma', (select id from employee_types where name = 'apprentice_nontech'), '2026-06-01', (select id from teams where name = 'Operations'), 'active'),
('Priya Verma', (select id from employee_types where name = 'apprentice_tech'), '2026-05-15', (select id from teams where name = 'Engineering'), 'active'),
('Rohan Gupta', (select id from employee_types where name = 'intern'), '2026-04-01', (select id from teams where name = 'Engineering'), 'active'),
('Sneha Iyer', (select id from employee_types where name = 'intern'), '2026-03-10', (select id from teams where name = 'Design'), 'active'),
('Vikram Singh', (select id from employee_types where name = 'fte'), '2025-08-01', (select id from teams where name = 'Engineering'), 'active'),
('Anjali Nair', (select id from employee_types where name = 'fte'), '2025-09-15', (select id from teams where name = 'Operations'), 'active'),
('Karan Mehta', (select id from employee_types where name = 'ftc'), '2026-01-10', (select id from teams where name = 'Finance'), 'active'),
('Divya Reddy', (select id from employee_types where name = 'ftc'), '2026-02-01', (select id from teams where name = 'Engineering'), 'active'),
('Arjun Kumar', (select id from employee_types where name = 'contractor'), '2026-07-01', (select id from teams where name = 'Design'), 'active'),
('Meera Joshi', (select id from employee_types where name = 'contractor'), '2026-06-15', (select id from teams where name = 'Operations'), 'active'),
('Rahul Desai', (select id from employee_types where name = 'apprentice_tech'), '2026-07-10', (select id from teams where name = 'Engineering'), 'active'),
('Pooja Nair', (select id from employee_types where name = 'apprentice_nontech'), '2026-07-05', (select id from teams where name = 'Operations'), 'active'),
('Aditya Rao', (select id from employee_types where name = 'intern'), '2026-02-20', (select id from teams where name = 'Engineering'), 'active'),
('Kavya Pillai', (select id from employee_types where name = 'fte'), '2025-10-01', (select id from teams where name = 'Design'), 'active'),
('Sanjay Patel', (select id from employee_types where name = 'ftc'), '2026-03-01', (select id from teams where name = 'Operations'), 'active');